name: License Scan

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master
      - develop
      - release
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install `fossa-cli`
        run: |
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash

      - name: Run & Upload Build Analysis
        run: |
          fossa init
          sfossa analyze
        env:
          FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
